// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/audit" | "/admin/employees" | "/admin/kiosks" | "/admin/muster" | "/admin/pin" | "/admin/settings" | "/admin/visitors" | "/visitor"
type AppRouteHandlerRoutes = "/api/admin/audit" | "/api/admin/audit/export" | "/api/admin/employees" | "/api/admin/employees/export" | "/api/admin/employees/import" | "/api/admin/kiosks" | "/api/admin/muster" | "/api/admin/pin" | "/api/admin/session" | "/api/admin/settings" | "/api/admin/visitors" | "/api/admin/visitors/reset" | "/api/employees" | "/api/health" | "/api/media/[id]/[kind]" | "/api/media/upload" | "/api/presence/toggle" | "/api/replication/forward" | "/api/replication/identity" | "/api/roster" | "/api/settings/training-expiry" | "/api/stream" | "/api/visitors/register" | "/api/visitors/search"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/audit": {}
  "/admin/employees": {}
  "/admin/kiosks": {}
  "/admin/muster": {}
  "/admin/pin": {}
  "/admin/settings": {}
  "/admin/visitors": {}
  "/api/admin/audit": {}
  "/api/admin/audit/export": {}
  "/api/admin/employees": {}
  "/api/admin/employees/export": {}
  "/api/admin/employees/import": {}
  "/api/admin/kiosks": {}
  "/api/admin/muster": {}
  "/api/admin/pin": {}
  "/api/admin/session": {}
  "/api/admin/settings": {}
  "/api/admin/visitors": {}
  "/api/admin/visitors/reset": {}
  "/api/employees": {}
  "/api/health": {}
  "/api/media/[id]/[kind]": { "id": string; "kind": string; }
  "/api/media/upload": {}
  "/api/presence/toggle": {}
  "/api/replication/forward": {}
  "/api/replication/identity": {}
  "/api/roster": {}
  "/api/settings/training-expiry": {}
  "/api/stream": {}
  "/api/visitors/register": {}
  "/api/visitors/search": {}
  "/visitor": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
