// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/employees">> = Specific
  const handler = {} as typeof import("../../src/app/admin/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/kiosks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kiosks">> = Specific
  const handler = {} as typeof import("../../src/app/admin/kiosks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/muster/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/muster">> = Specific
  const handler = {} as typeof import("../../src/app/admin/muster/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/visitors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/visitors">> = Specific
  const handler = {} as typeof import("../../src/app/admin/visitors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/visitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visitor">> = Specific
  const handler = {} as typeof import("../../src/app/visitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/audit/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/audit/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/employees/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/employees/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/employees/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/employees/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/employees/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/employees/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/employees">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/kiosks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/kiosks">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/kiosks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/muster/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/muster">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/muster/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pin">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/visitors/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/visitors/reset">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/visitors/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/visitors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/visitors">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/visitors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/[id]/[kind]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[id]/[kind]">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/[id]/[kind]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/presence/toggle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/presence/toggle">> = Specific
  const handler = {} as typeof import("../../src/app/api/presence/toggle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/replication/forward/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/replication/forward">> = Specific
  const handler = {} as typeof import("../../src/app/api/replication/forward/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/replication/identity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/replication/identity">> = Specific
  const handler = {} as typeof import("../../src/app/api/replication/identity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/roster/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roster">> = Specific
  const handler = {} as typeof import("../../src/app/api/roster/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/training-expiry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/training-expiry">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/training-expiry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/visitors/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitors/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/visitors/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/visitors/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitors/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/visitors/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
